container:
  version: postgres:12.19-alpine3.20

db:
  host: jdbc:postgresql://localhost:5432/admin
  user: admin
  password: admin321
  driver: org.postgresql.Driver

liquibase:
  defaultSchema: public
  currentSchema: public
  changeLogPath: db/changelog/changelog.xml

jwt:
  secretKey: 5f08c611830bbfd9cac714b267ac221b9ba3b3815d7bc9f9ed53c838eda88e2e9e576166ec00ddc73e91cd838541010670cc3dfdbebfb4b1d857e43658f5de01
  issuer: Coworking-service
  tokenLifetime: 43200000
